
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const UserRole = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN'
} as const

export type UserRole = (typeof UserRole)[keyof typeof UserRole]


export const UserStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE'
} as const

export type UserStatus = (typeof UserStatus)[keyof typeof UserStatus]


export const CommitteeRole = {
  PRESIDENT: 'PRESIDENT',
  VICE_PRESIDENT: 'VICE_PRESIDENT',
  SECRETARY: 'SECRETARY',
  ASSISTANT_SECRETARY: 'ASSISTANT_SECRETARY',
  TREASURER: 'TREASURER',
  MEMBER: 'MEMBER',
  IMAM: 'IMAM',
  MUAZZIN: 'MUAZZIN'
} as const

export type CommitteeRole = (typeof CommitteeRole)[keyof typeof CommitteeRole]


export const FamilyStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE'
} as const

export type FamilyStatus = (typeof FamilyStatus)[keyof typeof FamilyStatus]


export const CollectionStatus = {
  PAID: 'PAID',
  PARTIAL: 'PARTIAL',
  UNPAID: 'UNPAID'
} as const

export type CollectionStatus = (typeof CollectionStatus)[keyof typeof CollectionStatus]


export const ExpenseCategory = {
  IMAM_SALARY: 'IMAM_SALARY',
  MUAZZIN_SALARY: 'MUAZZIN_SALARY',
  ELECTRICITY: 'ELECTRICITY',
  WATER: 'WATER',
  CLEANING: 'CLEANING',
  MAINTENANCE: 'MAINTENANCE',
  DEVELOPMENT: 'DEVELOPMENT',
  OTHER: 'OTHER'
} as const

export type ExpenseCategory = (typeof ExpenseCategory)[keyof typeof ExpenseCategory]


export const ProjectStatus = {
  PLANNING: 'PLANNING',
  RUNNING: 'RUNNING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
} as const

export type ProjectStatus = (typeof ProjectStatus)[keyof typeof ProjectStatus]


export const Month = {
  JANUARY: 'JANUARY',
  FEBRUARY: 'FEBRUARY',
  MARCH: 'MARCH',
  APRIL: 'APRIL',
  MAY: 'MAY',
  JUNE: 'JUNE',
  JULY: 'JULY',
  AUGUST: 'AUGUST',
  SEPTEMBER: 'SEPTEMBER',
  OCTOBER: 'OCTOBER',
  NOVEMBER: 'NOVEMBER',
  DECEMBER: 'DECEMBER'
} as const

export type Month = (typeof Month)[keyof typeof Month]
