
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DevelopmentProject` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model DevelopmentProject
 * 
 */
export type DevelopmentProjectModel = runtime.Types.Result.DefaultSelection<Prisma.$DevelopmentProjectPayload>

export type AggregateDevelopmentProject = {
  _count: DevelopmentProjectCountAggregateOutputType | null
  _avg: DevelopmentProjectAvgAggregateOutputType | null
  _sum: DevelopmentProjectSumAggregateOutputType | null
  _min: DevelopmentProjectMinAggregateOutputType | null
  _max: DevelopmentProjectMaxAggregateOutputType | null
}

export type DevelopmentProjectAvgAggregateOutputType = {
  budget: runtime.Decimal | null
  spent: runtime.Decimal | null
  progress: number | null
}

export type DevelopmentProjectSumAggregateOutputType = {
  budget: runtime.Decimal | null
  spent: runtime.Decimal | null
  progress: number | null
}

export type DevelopmentProjectMinAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  budget: runtime.Decimal | null
  spent: runtime.Decimal | null
  progress: number | null
  image: string | null
  status: $Enums.ProjectStatus | null
  startDate: Date | null
  endDate: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DevelopmentProjectMaxAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  budget: runtime.Decimal | null
  spent: runtime.Decimal | null
  progress: number | null
  image: string | null
  status: $Enums.ProjectStatus | null
  startDate: Date | null
  endDate: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DevelopmentProjectCountAggregateOutputType = {
  id: number
  title: number
  description: number
  budget: number
  spent: number
  progress: number
  image: number
  status: number
  startDate: number
  endDate: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type DevelopmentProjectAvgAggregateInputType = {
  budget?: true
  spent?: true
  progress?: true
}

export type DevelopmentProjectSumAggregateInputType = {
  budget?: true
  spent?: true
  progress?: true
}

export type DevelopmentProjectMinAggregateInputType = {
  id?: true
  title?: true
  description?: true
  budget?: true
  spent?: true
  progress?: true
  image?: true
  status?: true
  startDate?: true
  endDate?: true
  createdAt?: true
  updatedAt?: true
}

export type DevelopmentProjectMaxAggregateInputType = {
  id?: true
  title?: true
  description?: true
  budget?: true
  spent?: true
  progress?: true
  image?: true
  status?: true
  startDate?: true
  endDate?: true
  createdAt?: true
  updatedAt?: true
}

export type DevelopmentProjectCountAggregateInputType = {
  id?: true
  title?: true
  description?: true
  budget?: true
  spent?: true
  progress?: true
  image?: true
  status?: true
  startDate?: true
  endDate?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type DevelopmentProjectAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DevelopmentProject to aggregate.
   */
  where?: Prisma.DevelopmentProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DevelopmentProjects to fetch.
   */
  orderBy?: Prisma.DevelopmentProjectOrderByWithRelationInput | Prisma.DevelopmentProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DevelopmentProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DevelopmentProjects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DevelopmentProjects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DevelopmentProjects
  **/
  _count?: true | DevelopmentProjectCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DevelopmentProjectAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DevelopmentProjectSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DevelopmentProjectMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DevelopmentProjectMaxAggregateInputType
}

export type GetDevelopmentProjectAggregateType<T extends DevelopmentProjectAggregateArgs> = {
      [P in keyof T & keyof AggregateDevelopmentProject]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDevelopmentProject[P]>
    : Prisma.GetScalarType<T[P], AggregateDevelopmentProject[P]>
}




export type DevelopmentProjectGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DevelopmentProjectWhereInput
  orderBy?: Prisma.DevelopmentProjectOrderByWithAggregationInput | Prisma.DevelopmentProjectOrderByWithAggregationInput[]
  by: Prisma.DevelopmentProjectScalarFieldEnum[] | Prisma.DevelopmentProjectScalarFieldEnum
  having?: Prisma.DevelopmentProjectScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DevelopmentProjectCountAggregateInputType | true
  _avg?: DevelopmentProjectAvgAggregateInputType
  _sum?: DevelopmentProjectSumAggregateInputType
  _min?: DevelopmentProjectMinAggregateInputType
  _max?: DevelopmentProjectMaxAggregateInputType
}

export type DevelopmentProjectGroupByOutputType = {
  id: string
  title: string
  description: string | null
  budget: runtime.Decimal | null
  spent: runtime.Decimal | null
  progress: number
  image: string | null
  status: $Enums.ProjectStatus
  startDate: Date | null
  endDate: Date | null
  createdAt: Date
  updatedAt: Date
  _count: DevelopmentProjectCountAggregateOutputType | null
  _avg: DevelopmentProjectAvgAggregateOutputType | null
  _sum: DevelopmentProjectSumAggregateOutputType | null
  _min: DevelopmentProjectMinAggregateOutputType | null
  _max: DevelopmentProjectMaxAggregateOutputType | null
}

export type GetDevelopmentProjectGroupByPayload<T extends DevelopmentProjectGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DevelopmentProjectGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DevelopmentProjectGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DevelopmentProjectGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DevelopmentProjectGroupByOutputType[P]>
      }
    >
  >



export type DevelopmentProjectWhereInput = {
  AND?: Prisma.DevelopmentProjectWhereInput | Prisma.DevelopmentProjectWhereInput[]
  OR?: Prisma.DevelopmentProjectWhereInput[]
  NOT?: Prisma.DevelopmentProjectWhereInput | Prisma.DevelopmentProjectWhereInput[]
  id?: Prisma.StringFilter<"DevelopmentProject"> | string
  title?: Prisma.StringFilter<"DevelopmentProject"> | string
  description?: Prisma.StringNullableFilter<"DevelopmentProject"> | string | null
  budget?: Prisma.DecimalNullableFilter<"DevelopmentProject"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  spent?: Prisma.DecimalNullableFilter<"DevelopmentProject"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  progress?: Prisma.IntFilter<"DevelopmentProject"> | number
  image?: Prisma.StringNullableFilter<"DevelopmentProject"> | string | null
  status?: Prisma.EnumProjectStatusFilter<"DevelopmentProject"> | $Enums.ProjectStatus
  startDate?: Prisma.DateTimeNullableFilter<"DevelopmentProject"> | Date | string | null
  endDate?: Prisma.DateTimeNullableFilter<"DevelopmentProject"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"DevelopmentProject"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DevelopmentProject"> | Date | string
}

export type DevelopmentProjectOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  budget?: Prisma.SortOrderInput | Prisma.SortOrder
  spent?: Prisma.SortOrderInput | Prisma.SortOrder
  progress?: Prisma.SortOrder
  image?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  startDate?: Prisma.SortOrderInput | Prisma.SortOrder
  endDate?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DevelopmentProjectWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.DevelopmentProjectWhereInput | Prisma.DevelopmentProjectWhereInput[]
  OR?: Prisma.DevelopmentProjectWhereInput[]
  NOT?: Prisma.DevelopmentProjectWhereInput | Prisma.DevelopmentProjectWhereInput[]
  title?: Prisma.StringFilter<"DevelopmentProject"> | string
  description?: Prisma.StringNullableFilter<"DevelopmentProject"> | string | null
  budget?: Prisma.DecimalNullableFilter<"DevelopmentProject"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  spent?: Prisma.DecimalNullableFilter<"DevelopmentProject"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  progress?: Prisma.IntFilter<"DevelopmentProject"> | number
  image?: Prisma.StringNullableFilter<"DevelopmentProject"> | string | null
  status?: Prisma.EnumProjectStatusFilter<"DevelopmentProject"> | $Enums.ProjectStatus
  startDate?: Prisma.DateTimeNullableFilter<"DevelopmentProject"> | Date | string | null
  endDate?: Prisma.DateTimeNullableFilter<"DevelopmentProject"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"DevelopmentProject"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DevelopmentProject"> | Date | string
}, "id">

export type DevelopmentProjectOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  budget?: Prisma.SortOrderInput | Prisma.SortOrder
  spent?: Prisma.SortOrderInput | Prisma.SortOrder
  progress?: Prisma.SortOrder
  image?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  startDate?: Prisma.SortOrderInput | Prisma.SortOrder
  endDate?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.DevelopmentProjectCountOrderByAggregateInput
  _avg?: Prisma.DevelopmentProjectAvgOrderByAggregateInput
  _max?: Prisma.DevelopmentProjectMaxOrderByAggregateInput
  _min?: Prisma.DevelopmentProjectMinOrderByAggregateInput
  _sum?: Prisma.DevelopmentProjectSumOrderByAggregateInput
}

export type DevelopmentProjectScalarWhereWithAggregatesInput = {
  AND?: Prisma.DevelopmentProjectScalarWhereWithAggregatesInput | Prisma.DevelopmentProjectScalarWhereWithAggregatesInput[]
  OR?: Prisma.DevelopmentProjectScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DevelopmentProjectScalarWhereWithAggregatesInput | Prisma.DevelopmentProjectScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"DevelopmentProject"> | string
  title?: Prisma.StringWithAggregatesFilter<"DevelopmentProject"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"DevelopmentProject"> | string | null
  budget?: Prisma.DecimalNullableWithAggregatesFilter<"DevelopmentProject"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  spent?: Prisma.DecimalNullableWithAggregatesFilter<"DevelopmentProject"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  progress?: Prisma.IntWithAggregatesFilter<"DevelopmentProject"> | number
  image?: Prisma.StringNullableWithAggregatesFilter<"DevelopmentProject"> | string | null
  status?: Prisma.EnumProjectStatusWithAggregatesFilter<"DevelopmentProject"> | $Enums.ProjectStatus
  startDate?: Prisma.DateTimeNullableWithAggregatesFilter<"DevelopmentProject"> | Date | string | null
  endDate?: Prisma.DateTimeNullableWithAggregatesFilter<"DevelopmentProject"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"DevelopmentProject"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"DevelopmentProject"> | Date | string
}

export type DevelopmentProjectCreateInput = {
  id?: string
  title: string
  description?: string | null
  budget?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  spent?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  progress?: number
  image?: string | null
  status?: $Enums.ProjectStatus
  startDate?: Date | string | null
  endDate?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DevelopmentProjectUncheckedCreateInput = {
  id?: string
  title: string
  description?: string | null
  budget?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  spent?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  progress?: number
  image?: string | null
  status?: $Enums.ProjectStatus
  startDate?: Date | string | null
  endDate?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DevelopmentProjectUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  budget?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  spent?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DevelopmentProjectUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  budget?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  spent?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DevelopmentProjectCreateManyInput = {
  id?: string
  title: string
  description?: string | null
  budget?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  spent?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  progress?: number
  image?: string | null
  status?: $Enums.ProjectStatus
  startDate?: Date | string | null
  endDate?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DevelopmentProjectUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  budget?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  spent?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DevelopmentProjectUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  budget?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  spent?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DevelopmentProjectCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  budget?: Prisma.SortOrder
  spent?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  image?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DevelopmentProjectAvgOrderByAggregateInput = {
  budget?: Prisma.SortOrder
  spent?: Prisma.SortOrder
  progress?: Prisma.SortOrder
}

export type DevelopmentProjectMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  budget?: Prisma.SortOrder
  spent?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  image?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DevelopmentProjectMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  budget?: Prisma.SortOrder
  spent?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  image?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DevelopmentProjectSumOrderByAggregateInput = {
  budget?: Prisma.SortOrder
  spent?: Prisma.SortOrder
  progress?: Prisma.SortOrder
}

export type NullableDecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type EnumProjectStatusFieldUpdateOperationsInput = {
  set?: $Enums.ProjectStatus
}



export type DevelopmentProjectSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  budget?: boolean
  spent?: boolean
  progress?: boolean
  image?: boolean
  status?: boolean
  startDate?: boolean
  endDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["developmentProject"]>

export type DevelopmentProjectSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  budget?: boolean
  spent?: boolean
  progress?: boolean
  image?: boolean
  status?: boolean
  startDate?: boolean
  endDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["developmentProject"]>

export type DevelopmentProjectSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  budget?: boolean
  spent?: boolean
  progress?: boolean
  image?: boolean
  status?: boolean
  startDate?: boolean
  endDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["developmentProject"]>

export type DevelopmentProjectSelectScalar = {
  id?: boolean
  title?: boolean
  description?: boolean
  budget?: boolean
  spent?: boolean
  progress?: boolean
  image?: boolean
  status?: boolean
  startDate?: boolean
  endDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type DevelopmentProjectOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "description" | "budget" | "spent" | "progress" | "image" | "status" | "startDate" | "endDate" | "createdAt" | "updatedAt", ExtArgs["result"]["developmentProject"]>

export type $DevelopmentProjectPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DevelopmentProject"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    description: string | null
    budget: runtime.Decimal | null
    spent: runtime.Decimal | null
    progress: number
    image: string | null
    status: $Enums.ProjectStatus
    startDate: Date | null
    endDate: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["developmentProject"]>
  composites: {}
}

export type DevelopmentProjectGetPayload<S extends boolean | null | undefined | DevelopmentProjectDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DevelopmentProjectPayload, S>

export type DevelopmentProjectCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DevelopmentProjectFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DevelopmentProjectCountAggregateInputType | true
  }

export interface DevelopmentProjectDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DevelopmentProject'], meta: { name: 'DevelopmentProject' } }
  /**
   * Find zero or one DevelopmentProject that matches the filter.
   * @param {DevelopmentProjectFindUniqueArgs} args - Arguments to find a DevelopmentProject
   * @example
   * // Get one DevelopmentProject
   * const developmentProject = await prisma.developmentProject.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DevelopmentProjectFindUniqueArgs>(args: Prisma.SelectSubset<T, DevelopmentProjectFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DevelopmentProjectClient<runtime.Types.Result.GetResult<Prisma.$DevelopmentProjectPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DevelopmentProject that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DevelopmentProjectFindUniqueOrThrowArgs} args - Arguments to find a DevelopmentProject
   * @example
   * // Get one DevelopmentProject
   * const developmentProject = await prisma.developmentProject.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DevelopmentProjectFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DevelopmentProjectFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DevelopmentProjectClient<runtime.Types.Result.GetResult<Prisma.$DevelopmentProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DevelopmentProject that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DevelopmentProjectFindFirstArgs} args - Arguments to find a DevelopmentProject
   * @example
   * // Get one DevelopmentProject
   * const developmentProject = await prisma.developmentProject.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DevelopmentProjectFindFirstArgs>(args?: Prisma.SelectSubset<T, DevelopmentProjectFindFirstArgs<ExtArgs>>): Prisma.Prisma__DevelopmentProjectClient<runtime.Types.Result.GetResult<Prisma.$DevelopmentProjectPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DevelopmentProject that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DevelopmentProjectFindFirstOrThrowArgs} args - Arguments to find a DevelopmentProject
   * @example
   * // Get one DevelopmentProject
   * const developmentProject = await prisma.developmentProject.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DevelopmentProjectFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DevelopmentProjectFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DevelopmentProjectClient<runtime.Types.Result.GetResult<Prisma.$DevelopmentProjectPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DevelopmentProjects that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DevelopmentProjectFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DevelopmentProjects
   * const developmentProjects = await prisma.developmentProject.findMany()
   * 
   * // Get first 10 DevelopmentProjects
   * const developmentProjects = await prisma.developmentProject.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const developmentProjectWithIdOnly = await prisma.developmentProject.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DevelopmentProjectFindManyArgs>(args?: Prisma.SelectSubset<T, DevelopmentProjectFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DevelopmentProjectPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DevelopmentProject.
   * @param {DevelopmentProjectCreateArgs} args - Arguments to create a DevelopmentProject.
   * @example
   * // Create one DevelopmentProject
   * const DevelopmentProject = await prisma.developmentProject.create({
   *   data: {
   *     // ... data to create a DevelopmentProject
   *   }
   * })
   * 
   */
  create<T extends DevelopmentProjectCreateArgs>(args: Prisma.SelectSubset<T, DevelopmentProjectCreateArgs<ExtArgs>>): Prisma.Prisma__DevelopmentProjectClient<runtime.Types.Result.GetResult<Prisma.$DevelopmentProjectPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DevelopmentProjects.
   * @param {DevelopmentProjectCreateManyArgs} args - Arguments to create many DevelopmentProjects.
   * @example
   * // Create many DevelopmentProjects
   * const developmentProject = await prisma.developmentProject.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DevelopmentProjectCreateManyArgs>(args?: Prisma.SelectSubset<T, DevelopmentProjectCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DevelopmentProjects and returns the data saved in the database.
   * @param {DevelopmentProjectCreateManyAndReturnArgs} args - Arguments to create many DevelopmentProjects.
   * @example
   * // Create many DevelopmentProjects
   * const developmentProject = await prisma.developmentProject.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DevelopmentProjects and only return the `id`
   * const developmentProjectWithIdOnly = await prisma.developmentProject.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DevelopmentProjectCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DevelopmentProjectCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DevelopmentProjectPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DevelopmentProject.
   * @param {DevelopmentProjectDeleteArgs} args - Arguments to delete one DevelopmentProject.
   * @example
   * // Delete one DevelopmentProject
   * const DevelopmentProject = await prisma.developmentProject.delete({
   *   where: {
   *     // ... filter to delete one DevelopmentProject
   *   }
   * })
   * 
   */
  delete<T extends DevelopmentProjectDeleteArgs>(args: Prisma.SelectSubset<T, DevelopmentProjectDeleteArgs<ExtArgs>>): Prisma.Prisma__DevelopmentProjectClient<runtime.Types.Result.GetResult<Prisma.$DevelopmentProjectPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DevelopmentProject.
   * @param {DevelopmentProjectUpdateArgs} args - Arguments to update one DevelopmentProject.
   * @example
   * // Update one DevelopmentProject
   * const developmentProject = await prisma.developmentProject.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DevelopmentProjectUpdateArgs>(args: Prisma.SelectSubset<T, DevelopmentProjectUpdateArgs<ExtArgs>>): Prisma.Prisma__DevelopmentProjectClient<runtime.Types.Result.GetResult<Prisma.$DevelopmentProjectPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DevelopmentProjects.
   * @param {DevelopmentProjectDeleteManyArgs} args - Arguments to filter DevelopmentProjects to delete.
   * @example
   * // Delete a few DevelopmentProjects
   * const { count } = await prisma.developmentProject.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DevelopmentProjectDeleteManyArgs>(args?: Prisma.SelectSubset<T, DevelopmentProjectDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DevelopmentProjects.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DevelopmentProjectUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DevelopmentProjects
   * const developmentProject = await prisma.developmentProject.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DevelopmentProjectUpdateManyArgs>(args: Prisma.SelectSubset<T, DevelopmentProjectUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DevelopmentProjects and returns the data updated in the database.
   * @param {DevelopmentProjectUpdateManyAndReturnArgs} args - Arguments to update many DevelopmentProjects.
   * @example
   * // Update many DevelopmentProjects
   * const developmentProject = await prisma.developmentProject.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DevelopmentProjects and only return the `id`
   * const developmentProjectWithIdOnly = await prisma.developmentProject.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DevelopmentProjectUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DevelopmentProjectUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DevelopmentProjectPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DevelopmentProject.
   * @param {DevelopmentProjectUpsertArgs} args - Arguments to update or create a DevelopmentProject.
   * @example
   * // Update or create a DevelopmentProject
   * const developmentProject = await prisma.developmentProject.upsert({
   *   create: {
   *     // ... data to create a DevelopmentProject
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DevelopmentProject we want to update
   *   }
   * })
   */
  upsert<T extends DevelopmentProjectUpsertArgs>(args: Prisma.SelectSubset<T, DevelopmentProjectUpsertArgs<ExtArgs>>): Prisma.Prisma__DevelopmentProjectClient<runtime.Types.Result.GetResult<Prisma.$DevelopmentProjectPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DevelopmentProjects.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DevelopmentProjectCountArgs} args - Arguments to filter DevelopmentProjects to count.
   * @example
   * // Count the number of DevelopmentProjects
   * const count = await prisma.developmentProject.count({
   *   where: {
   *     // ... the filter for the DevelopmentProjects we want to count
   *   }
   * })
  **/
  count<T extends DevelopmentProjectCountArgs>(
    args?: Prisma.Subset<T, DevelopmentProjectCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DevelopmentProjectCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DevelopmentProject.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DevelopmentProjectAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DevelopmentProjectAggregateArgs>(args: Prisma.Subset<T, DevelopmentProjectAggregateArgs>): Prisma.PrismaPromise<GetDevelopmentProjectAggregateType<T>>

  /**
   * Group by DevelopmentProject.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DevelopmentProjectGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DevelopmentProjectGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DevelopmentProjectGroupByArgs['orderBy'] }
      : { orderBy?: DevelopmentProjectGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DevelopmentProjectGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDevelopmentProjectGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DevelopmentProject model
 */
readonly fields: DevelopmentProjectFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DevelopmentProject.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DevelopmentProjectClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DevelopmentProject model
 */
export interface DevelopmentProjectFieldRefs {
  readonly id: Prisma.FieldRef<"DevelopmentProject", 'String'>
  readonly title: Prisma.FieldRef<"DevelopmentProject", 'String'>
  readonly description: Prisma.FieldRef<"DevelopmentProject", 'String'>
  readonly budget: Prisma.FieldRef<"DevelopmentProject", 'Decimal'>
  readonly spent: Prisma.FieldRef<"DevelopmentProject", 'Decimal'>
  readonly progress: Prisma.FieldRef<"DevelopmentProject", 'Int'>
  readonly image: Prisma.FieldRef<"DevelopmentProject", 'String'>
  readonly status: Prisma.FieldRef<"DevelopmentProject", 'ProjectStatus'>
  readonly startDate: Prisma.FieldRef<"DevelopmentProject", 'DateTime'>
  readonly endDate: Prisma.FieldRef<"DevelopmentProject", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"DevelopmentProject", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"DevelopmentProject", 'DateTime'>
}
    

// Custom InputTypes
/**
 * DevelopmentProject findUnique
 */
export type DevelopmentProjectFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DevelopmentProject
   */
  select?: Prisma.DevelopmentProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DevelopmentProject
   */
  omit?: Prisma.DevelopmentProjectOmit<ExtArgs> | null
  /**
   * Filter, which DevelopmentProject to fetch.
   */
  where: Prisma.DevelopmentProjectWhereUniqueInput
}

/**
 * DevelopmentProject findUniqueOrThrow
 */
export type DevelopmentProjectFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DevelopmentProject
   */
  select?: Prisma.DevelopmentProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DevelopmentProject
   */
  omit?: Prisma.DevelopmentProjectOmit<ExtArgs> | null
  /**
   * Filter, which DevelopmentProject to fetch.
   */
  where: Prisma.DevelopmentProjectWhereUniqueInput
}

/**
 * DevelopmentProject findFirst
 */
export type DevelopmentProjectFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DevelopmentProject
   */
  select?: Prisma.DevelopmentProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DevelopmentProject
   */
  omit?: Prisma.DevelopmentProjectOmit<ExtArgs> | null
  /**
   * Filter, which DevelopmentProject to fetch.
   */
  where?: Prisma.DevelopmentProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DevelopmentProjects to fetch.
   */
  orderBy?: Prisma.DevelopmentProjectOrderByWithRelationInput | Prisma.DevelopmentProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DevelopmentProjects.
   */
  cursor?: Prisma.DevelopmentProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DevelopmentProjects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DevelopmentProjects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DevelopmentProjects.
   */
  distinct?: Prisma.DevelopmentProjectScalarFieldEnum | Prisma.DevelopmentProjectScalarFieldEnum[]
}

/**
 * DevelopmentProject findFirstOrThrow
 */
export type DevelopmentProjectFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DevelopmentProject
   */
  select?: Prisma.DevelopmentProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DevelopmentProject
   */
  omit?: Prisma.DevelopmentProjectOmit<ExtArgs> | null
  /**
   * Filter, which DevelopmentProject to fetch.
   */
  where?: Prisma.DevelopmentProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DevelopmentProjects to fetch.
   */
  orderBy?: Prisma.DevelopmentProjectOrderByWithRelationInput | Prisma.DevelopmentProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DevelopmentProjects.
   */
  cursor?: Prisma.DevelopmentProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DevelopmentProjects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DevelopmentProjects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DevelopmentProjects.
   */
  distinct?: Prisma.DevelopmentProjectScalarFieldEnum | Prisma.DevelopmentProjectScalarFieldEnum[]
}

/**
 * DevelopmentProject findMany
 */
export type DevelopmentProjectFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DevelopmentProject
   */
  select?: Prisma.DevelopmentProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DevelopmentProject
   */
  omit?: Prisma.DevelopmentProjectOmit<ExtArgs> | null
  /**
   * Filter, which DevelopmentProjects to fetch.
   */
  where?: Prisma.DevelopmentProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DevelopmentProjects to fetch.
   */
  orderBy?: Prisma.DevelopmentProjectOrderByWithRelationInput | Prisma.DevelopmentProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DevelopmentProjects.
   */
  cursor?: Prisma.DevelopmentProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DevelopmentProjects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DevelopmentProjects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DevelopmentProjects.
   */
  distinct?: Prisma.DevelopmentProjectScalarFieldEnum | Prisma.DevelopmentProjectScalarFieldEnum[]
}

/**
 * DevelopmentProject create
 */
export type DevelopmentProjectCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DevelopmentProject
   */
  select?: Prisma.DevelopmentProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DevelopmentProject
   */
  omit?: Prisma.DevelopmentProjectOmit<ExtArgs> | null
  /**
   * The data needed to create a DevelopmentProject.
   */
  data: Prisma.XOR<Prisma.DevelopmentProjectCreateInput, Prisma.DevelopmentProjectUncheckedCreateInput>
}

/**
 * DevelopmentProject createMany
 */
export type DevelopmentProjectCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DevelopmentProjects.
   */
  data: Prisma.DevelopmentProjectCreateManyInput | Prisma.DevelopmentProjectCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DevelopmentProject createManyAndReturn
 */
export type DevelopmentProjectCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DevelopmentProject
   */
  select?: Prisma.DevelopmentProjectSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DevelopmentProject
   */
  omit?: Prisma.DevelopmentProjectOmit<ExtArgs> | null
  /**
   * The data used to create many DevelopmentProjects.
   */
  data: Prisma.DevelopmentProjectCreateManyInput | Prisma.DevelopmentProjectCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DevelopmentProject update
 */
export type DevelopmentProjectUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DevelopmentProject
   */
  select?: Prisma.DevelopmentProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DevelopmentProject
   */
  omit?: Prisma.DevelopmentProjectOmit<ExtArgs> | null
  /**
   * The data needed to update a DevelopmentProject.
   */
  data: Prisma.XOR<Prisma.DevelopmentProjectUpdateInput, Prisma.DevelopmentProjectUncheckedUpdateInput>
  /**
   * Choose, which DevelopmentProject to update.
   */
  where: Prisma.DevelopmentProjectWhereUniqueInput
}

/**
 * DevelopmentProject updateMany
 */
export type DevelopmentProjectUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DevelopmentProjects.
   */
  data: Prisma.XOR<Prisma.DevelopmentProjectUpdateManyMutationInput, Prisma.DevelopmentProjectUncheckedUpdateManyInput>
  /**
   * Filter which DevelopmentProjects to update
   */
  where?: Prisma.DevelopmentProjectWhereInput
  /**
   * Limit how many DevelopmentProjects to update.
   */
  limit?: number
}

/**
 * DevelopmentProject updateManyAndReturn
 */
export type DevelopmentProjectUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DevelopmentProject
   */
  select?: Prisma.DevelopmentProjectSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DevelopmentProject
   */
  omit?: Prisma.DevelopmentProjectOmit<ExtArgs> | null
  /**
   * The data used to update DevelopmentProjects.
   */
  data: Prisma.XOR<Prisma.DevelopmentProjectUpdateManyMutationInput, Prisma.DevelopmentProjectUncheckedUpdateManyInput>
  /**
   * Filter which DevelopmentProjects to update
   */
  where?: Prisma.DevelopmentProjectWhereInput
  /**
   * Limit how many DevelopmentProjects to update.
   */
  limit?: number
}

/**
 * DevelopmentProject upsert
 */
export type DevelopmentProjectUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DevelopmentProject
   */
  select?: Prisma.DevelopmentProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DevelopmentProject
   */
  omit?: Prisma.DevelopmentProjectOmit<ExtArgs> | null
  /**
   * The filter to search for the DevelopmentProject to update in case it exists.
   */
  where: Prisma.DevelopmentProjectWhereUniqueInput
  /**
   * In case the DevelopmentProject found by the `where` argument doesn't exist, create a new DevelopmentProject with this data.
   */
  create: Prisma.XOR<Prisma.DevelopmentProjectCreateInput, Prisma.DevelopmentProjectUncheckedCreateInput>
  /**
   * In case the DevelopmentProject was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DevelopmentProjectUpdateInput, Prisma.DevelopmentProjectUncheckedUpdateInput>
}

/**
 * DevelopmentProject delete
 */
export type DevelopmentProjectDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DevelopmentProject
   */
  select?: Prisma.DevelopmentProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DevelopmentProject
   */
  omit?: Prisma.DevelopmentProjectOmit<ExtArgs> | null
  /**
   * Filter which DevelopmentProject to delete.
   */
  where: Prisma.DevelopmentProjectWhereUniqueInput
}

/**
 * DevelopmentProject deleteMany
 */
export type DevelopmentProjectDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DevelopmentProjects to delete
   */
  where?: Prisma.DevelopmentProjectWhereInput
  /**
   * Limit how many DevelopmentProjects to delete.
   */
  limit?: number
}

/**
 * DevelopmentProject without action
 */
export type DevelopmentProjectDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DevelopmentProject
   */
  select?: Prisma.DevelopmentProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DevelopmentProject
   */
  omit?: Prisma.DevelopmentProjectOmit<ExtArgs> | null
}
