
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Family` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Family
 * 
 */
export type FamilyModel = runtime.Types.Result.DefaultSelection<Prisma.$FamilyPayload>

export type AggregateFamily = {
  _count: FamilyCountAggregateOutputType | null
  _avg: FamilyAvgAggregateOutputType | null
  _sum: FamilySumAggregateOutputType | null
  _min: FamilyMinAggregateOutputType | null
  _max: FamilyMaxAggregateOutputType | null
}

export type FamilyAvgAggregateOutputType = {
  monthlyFee: runtime.Decimal | null
  memberCount: number | null
}

export type FamilySumAggregateOutputType = {
  monthlyFee: runtime.Decimal | null
  memberCount: number | null
}

export type FamilyMinAggregateOutputType = {
  id: string | null
  familyCode: string | null
  headName: string | null
  phone: string | null
  address: string | null
  monthlyFee: runtime.Decimal | null
  memberCount: number | null
  joiningDate: Date | null
  status: $Enums.FamilyStatus | null
  remarks: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FamilyMaxAggregateOutputType = {
  id: string | null
  familyCode: string | null
  headName: string | null
  phone: string | null
  address: string | null
  monthlyFee: runtime.Decimal | null
  memberCount: number | null
  joiningDate: Date | null
  status: $Enums.FamilyStatus | null
  remarks: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FamilyCountAggregateOutputType = {
  id: number
  familyCode: number
  headName: number
  phone: number
  address: number
  monthlyFee: number
  memberCount: number
  joiningDate: number
  status: number
  remarks: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type FamilyAvgAggregateInputType = {
  monthlyFee?: true
  memberCount?: true
}

export type FamilySumAggregateInputType = {
  monthlyFee?: true
  memberCount?: true
}

export type FamilyMinAggregateInputType = {
  id?: true
  familyCode?: true
  headName?: true
  phone?: true
  address?: true
  monthlyFee?: true
  memberCount?: true
  joiningDate?: true
  status?: true
  remarks?: true
  createdAt?: true
  updatedAt?: true
}

export type FamilyMaxAggregateInputType = {
  id?: true
  familyCode?: true
  headName?: true
  phone?: true
  address?: true
  monthlyFee?: true
  memberCount?: true
  joiningDate?: true
  status?: true
  remarks?: true
  createdAt?: true
  updatedAt?: true
}

export type FamilyCountAggregateInputType = {
  id?: true
  familyCode?: true
  headName?: true
  phone?: true
  address?: true
  monthlyFee?: true
  memberCount?: true
  joiningDate?: true
  status?: true
  remarks?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type FamilyAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Family to aggregate.
   */
  where?: Prisma.FamilyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Families to fetch.
   */
  orderBy?: Prisma.FamilyOrderByWithRelationInput | Prisma.FamilyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FamilyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Families from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Families.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Families
  **/
  _count?: true | FamilyCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: FamilyAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: FamilySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FamilyMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FamilyMaxAggregateInputType
}

export type GetFamilyAggregateType<T extends FamilyAggregateArgs> = {
      [P in keyof T & keyof AggregateFamily]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFamily[P]>
    : Prisma.GetScalarType<T[P], AggregateFamily[P]>
}




export type FamilyGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FamilyWhereInput
  orderBy?: Prisma.FamilyOrderByWithAggregationInput | Prisma.FamilyOrderByWithAggregationInput[]
  by: Prisma.FamilyScalarFieldEnum[] | Prisma.FamilyScalarFieldEnum
  having?: Prisma.FamilyScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FamilyCountAggregateInputType | true
  _avg?: FamilyAvgAggregateInputType
  _sum?: FamilySumAggregateInputType
  _min?: FamilyMinAggregateInputType
  _max?: FamilyMaxAggregateInputType
}

export type FamilyGroupByOutputType = {
  id: string
  familyCode: string
  headName: string
  phone: string | null
  address: string
  monthlyFee: runtime.Decimal
  memberCount: number
  joiningDate: Date | null
  status: $Enums.FamilyStatus
  remarks: string | null
  createdAt: Date
  updatedAt: Date
  _count: FamilyCountAggregateOutputType | null
  _avg: FamilyAvgAggregateOutputType | null
  _sum: FamilySumAggregateOutputType | null
  _min: FamilyMinAggregateOutputType | null
  _max: FamilyMaxAggregateOutputType | null
}

export type GetFamilyGroupByPayload<T extends FamilyGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FamilyGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FamilyGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FamilyGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FamilyGroupByOutputType[P]>
      }
    >
  >



export type FamilyWhereInput = {
  AND?: Prisma.FamilyWhereInput | Prisma.FamilyWhereInput[]
  OR?: Prisma.FamilyWhereInput[]
  NOT?: Prisma.FamilyWhereInput | Prisma.FamilyWhereInput[]
  id?: Prisma.StringFilter<"Family"> | string
  familyCode?: Prisma.StringFilter<"Family"> | string
  headName?: Prisma.StringFilter<"Family"> | string
  phone?: Prisma.StringNullableFilter<"Family"> | string | null
  address?: Prisma.StringFilter<"Family"> | string
  monthlyFee?: Prisma.DecimalFilter<"Family"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  memberCount?: Prisma.IntFilter<"Family"> | number
  joiningDate?: Prisma.DateTimeNullableFilter<"Family"> | Date | string | null
  status?: Prisma.EnumFamilyStatusFilter<"Family"> | $Enums.FamilyStatus
  remarks?: Prisma.StringNullableFilter<"Family"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Family"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Family"> | Date | string
  collections?: Prisma.CollectionListRelationFilter
}

export type FamilyOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  familyCode?: Prisma.SortOrder
  headName?: Prisma.SortOrder
  phone?: Prisma.SortOrderInput | Prisma.SortOrder
  address?: Prisma.SortOrder
  monthlyFee?: Prisma.SortOrder
  memberCount?: Prisma.SortOrder
  joiningDate?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  remarks?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  collections?: Prisma.CollectionOrderByRelationAggregateInput
}

export type FamilyWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  familyCode?: string
  AND?: Prisma.FamilyWhereInput | Prisma.FamilyWhereInput[]
  OR?: Prisma.FamilyWhereInput[]
  NOT?: Prisma.FamilyWhereInput | Prisma.FamilyWhereInput[]
  headName?: Prisma.StringFilter<"Family"> | string
  phone?: Prisma.StringNullableFilter<"Family"> | string | null
  address?: Prisma.StringFilter<"Family"> | string
  monthlyFee?: Prisma.DecimalFilter<"Family"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  memberCount?: Prisma.IntFilter<"Family"> | number
  joiningDate?: Prisma.DateTimeNullableFilter<"Family"> | Date | string | null
  status?: Prisma.EnumFamilyStatusFilter<"Family"> | $Enums.FamilyStatus
  remarks?: Prisma.StringNullableFilter<"Family"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Family"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Family"> | Date | string
  collections?: Prisma.CollectionListRelationFilter
}, "id" | "familyCode">

export type FamilyOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  familyCode?: Prisma.SortOrder
  headName?: Prisma.SortOrder
  phone?: Prisma.SortOrderInput | Prisma.SortOrder
  address?: Prisma.SortOrder
  monthlyFee?: Prisma.SortOrder
  memberCount?: Prisma.SortOrder
  joiningDate?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  remarks?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.FamilyCountOrderByAggregateInput
  _avg?: Prisma.FamilyAvgOrderByAggregateInput
  _max?: Prisma.FamilyMaxOrderByAggregateInput
  _min?: Prisma.FamilyMinOrderByAggregateInput
  _sum?: Prisma.FamilySumOrderByAggregateInput
}

export type FamilyScalarWhereWithAggregatesInput = {
  AND?: Prisma.FamilyScalarWhereWithAggregatesInput | Prisma.FamilyScalarWhereWithAggregatesInput[]
  OR?: Prisma.FamilyScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FamilyScalarWhereWithAggregatesInput | Prisma.FamilyScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Family"> | string
  familyCode?: Prisma.StringWithAggregatesFilter<"Family"> | string
  headName?: Prisma.StringWithAggregatesFilter<"Family"> | string
  phone?: Prisma.StringNullableWithAggregatesFilter<"Family"> | string | null
  address?: Prisma.StringWithAggregatesFilter<"Family"> | string
  monthlyFee?: Prisma.DecimalWithAggregatesFilter<"Family"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  memberCount?: Prisma.IntWithAggregatesFilter<"Family"> | number
  joiningDate?: Prisma.DateTimeNullableWithAggregatesFilter<"Family"> | Date | string | null
  status?: Prisma.EnumFamilyStatusWithAggregatesFilter<"Family"> | $Enums.FamilyStatus
  remarks?: Prisma.StringNullableWithAggregatesFilter<"Family"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Family"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Family"> | Date | string
}

export type FamilyCreateInput = {
  id?: string
  familyCode: string
  headName: string
  phone?: string | null
  address: string
  monthlyFee: runtime.Decimal | runtime.DecimalJsLike | number | string
  memberCount?: number
  joiningDate?: Date | string | null
  status?: $Enums.FamilyStatus
  remarks?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  collections?: Prisma.CollectionCreateNestedManyWithoutFamilyInput
}

export type FamilyUncheckedCreateInput = {
  id?: string
  familyCode: string
  headName: string
  phone?: string | null
  address: string
  monthlyFee: runtime.Decimal | runtime.DecimalJsLike | number | string
  memberCount?: number
  joiningDate?: Date | string | null
  status?: $Enums.FamilyStatus
  remarks?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  collections?: Prisma.CollectionUncheckedCreateNestedManyWithoutFamilyInput
}

export type FamilyUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  familyCode?: Prisma.StringFieldUpdateOperationsInput | string
  headName?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyFee?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  memberCount?: Prisma.IntFieldUpdateOperationsInput | number
  joiningDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.EnumFamilyStatusFieldUpdateOperationsInput | $Enums.FamilyStatus
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  collections?: Prisma.CollectionUpdateManyWithoutFamilyNestedInput
}

export type FamilyUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  familyCode?: Prisma.StringFieldUpdateOperationsInput | string
  headName?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyFee?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  memberCount?: Prisma.IntFieldUpdateOperationsInput | number
  joiningDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.EnumFamilyStatusFieldUpdateOperationsInput | $Enums.FamilyStatus
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  collections?: Prisma.CollectionUncheckedUpdateManyWithoutFamilyNestedInput
}

export type FamilyCreateManyInput = {
  id?: string
  familyCode: string
  headName: string
  phone?: string | null
  address: string
  monthlyFee: runtime.Decimal | runtime.DecimalJsLike | number | string
  memberCount?: number
  joiningDate?: Date | string | null
  status?: $Enums.FamilyStatus
  remarks?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FamilyUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  familyCode?: Prisma.StringFieldUpdateOperationsInput | string
  headName?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyFee?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  memberCount?: Prisma.IntFieldUpdateOperationsInput | number
  joiningDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.EnumFamilyStatusFieldUpdateOperationsInput | $Enums.FamilyStatus
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FamilyUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  familyCode?: Prisma.StringFieldUpdateOperationsInput | string
  headName?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyFee?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  memberCount?: Prisma.IntFieldUpdateOperationsInput | number
  joiningDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.EnumFamilyStatusFieldUpdateOperationsInput | $Enums.FamilyStatus
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FamilyCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  familyCode?: Prisma.SortOrder
  headName?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  address?: Prisma.SortOrder
  monthlyFee?: Prisma.SortOrder
  memberCount?: Prisma.SortOrder
  joiningDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  remarks?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FamilyAvgOrderByAggregateInput = {
  monthlyFee?: Prisma.SortOrder
  memberCount?: Prisma.SortOrder
}

export type FamilyMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  familyCode?: Prisma.SortOrder
  headName?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  address?: Prisma.SortOrder
  monthlyFee?: Prisma.SortOrder
  memberCount?: Prisma.SortOrder
  joiningDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  remarks?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FamilyMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  familyCode?: Prisma.SortOrder
  headName?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  address?: Prisma.SortOrder
  monthlyFee?: Prisma.SortOrder
  memberCount?: Prisma.SortOrder
  joiningDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  remarks?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FamilySumOrderByAggregateInput = {
  monthlyFee?: Prisma.SortOrder
  memberCount?: Prisma.SortOrder
}

export type FamilyScalarRelationFilter = {
  is?: Prisma.FamilyWhereInput
  isNot?: Prisma.FamilyWhereInput
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type EnumFamilyStatusFieldUpdateOperationsInput = {
  set?: $Enums.FamilyStatus
}

export type FamilyCreateNestedOneWithoutCollectionsInput = {
  create?: Prisma.XOR<Prisma.FamilyCreateWithoutCollectionsInput, Prisma.FamilyUncheckedCreateWithoutCollectionsInput>
  connectOrCreate?: Prisma.FamilyCreateOrConnectWithoutCollectionsInput
  connect?: Prisma.FamilyWhereUniqueInput
}

export type FamilyUpdateOneRequiredWithoutCollectionsNestedInput = {
  create?: Prisma.XOR<Prisma.FamilyCreateWithoutCollectionsInput, Prisma.FamilyUncheckedCreateWithoutCollectionsInput>
  connectOrCreate?: Prisma.FamilyCreateOrConnectWithoutCollectionsInput
  upsert?: Prisma.FamilyUpsertWithoutCollectionsInput
  connect?: Prisma.FamilyWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FamilyUpdateToOneWithWhereWithoutCollectionsInput, Prisma.FamilyUpdateWithoutCollectionsInput>, Prisma.FamilyUncheckedUpdateWithoutCollectionsInput>
}

export type FamilyCreateWithoutCollectionsInput = {
  id?: string
  familyCode: string
  headName: string
  phone?: string | null
  address: string
  monthlyFee: runtime.Decimal | runtime.DecimalJsLike | number | string
  memberCount?: number
  joiningDate?: Date | string | null
  status?: $Enums.FamilyStatus
  remarks?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FamilyUncheckedCreateWithoutCollectionsInput = {
  id?: string
  familyCode: string
  headName: string
  phone?: string | null
  address: string
  monthlyFee: runtime.Decimal | runtime.DecimalJsLike | number | string
  memberCount?: number
  joiningDate?: Date | string | null
  status?: $Enums.FamilyStatus
  remarks?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FamilyCreateOrConnectWithoutCollectionsInput = {
  where: Prisma.FamilyWhereUniqueInput
  create: Prisma.XOR<Prisma.FamilyCreateWithoutCollectionsInput, Prisma.FamilyUncheckedCreateWithoutCollectionsInput>
}

export type FamilyUpsertWithoutCollectionsInput = {
  update: Prisma.XOR<Prisma.FamilyUpdateWithoutCollectionsInput, Prisma.FamilyUncheckedUpdateWithoutCollectionsInput>
  create: Prisma.XOR<Prisma.FamilyCreateWithoutCollectionsInput, Prisma.FamilyUncheckedCreateWithoutCollectionsInput>
  where?: Prisma.FamilyWhereInput
}

export type FamilyUpdateToOneWithWhereWithoutCollectionsInput = {
  where?: Prisma.FamilyWhereInput
  data: Prisma.XOR<Prisma.FamilyUpdateWithoutCollectionsInput, Prisma.FamilyUncheckedUpdateWithoutCollectionsInput>
}

export type FamilyUpdateWithoutCollectionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  familyCode?: Prisma.StringFieldUpdateOperationsInput | string
  headName?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyFee?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  memberCount?: Prisma.IntFieldUpdateOperationsInput | number
  joiningDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.EnumFamilyStatusFieldUpdateOperationsInput | $Enums.FamilyStatus
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FamilyUncheckedUpdateWithoutCollectionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  familyCode?: Prisma.StringFieldUpdateOperationsInput | string
  headName?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyFee?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  memberCount?: Prisma.IntFieldUpdateOperationsInput | number
  joiningDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.EnumFamilyStatusFieldUpdateOperationsInput | $Enums.FamilyStatus
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type FamilyCountOutputType
 */

export type FamilyCountOutputType = {
  collections: number
}

export type FamilyCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  collections?: boolean | FamilyCountOutputTypeCountCollectionsArgs
}

/**
 * FamilyCountOutputType without action
 */
export type FamilyCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FamilyCountOutputType
   */
  select?: Prisma.FamilyCountOutputTypeSelect<ExtArgs> | null
}

/**
 * FamilyCountOutputType without action
 */
export type FamilyCountOutputTypeCountCollectionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CollectionWhereInput
}


export type FamilySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  familyCode?: boolean
  headName?: boolean
  phone?: boolean
  address?: boolean
  monthlyFee?: boolean
  memberCount?: boolean
  joiningDate?: boolean
  status?: boolean
  remarks?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  collections?: boolean | Prisma.Family$collectionsArgs<ExtArgs>
  _count?: boolean | Prisma.FamilyCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["family"]>

export type FamilySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  familyCode?: boolean
  headName?: boolean
  phone?: boolean
  address?: boolean
  monthlyFee?: boolean
  memberCount?: boolean
  joiningDate?: boolean
  status?: boolean
  remarks?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["family"]>

export type FamilySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  familyCode?: boolean
  headName?: boolean
  phone?: boolean
  address?: boolean
  monthlyFee?: boolean
  memberCount?: boolean
  joiningDate?: boolean
  status?: boolean
  remarks?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["family"]>

export type FamilySelectScalar = {
  id?: boolean
  familyCode?: boolean
  headName?: boolean
  phone?: boolean
  address?: boolean
  monthlyFee?: boolean
  memberCount?: boolean
  joiningDate?: boolean
  status?: boolean
  remarks?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type FamilyOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "familyCode" | "headName" | "phone" | "address" | "monthlyFee" | "memberCount" | "joiningDate" | "status" | "remarks" | "createdAt" | "updatedAt", ExtArgs["result"]["family"]>
export type FamilyInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  collections?: boolean | Prisma.Family$collectionsArgs<ExtArgs>
  _count?: boolean | Prisma.FamilyCountOutputTypeDefaultArgs<ExtArgs>
}
export type FamilyIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type FamilyIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $FamilyPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Family"
  objects: {
    collections: Prisma.$CollectionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    familyCode: string
    headName: string
    phone: string | null
    address: string
    monthlyFee: runtime.Decimal
    memberCount: number
    joiningDate: Date | null
    status: $Enums.FamilyStatus
    remarks: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["family"]>
  composites: {}
}

export type FamilyGetPayload<S extends boolean | null | undefined | FamilyDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FamilyPayload, S>

export type FamilyCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FamilyFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FamilyCountAggregateInputType | true
  }

export interface FamilyDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Family'], meta: { name: 'Family' } }
  /**
   * Find zero or one Family that matches the filter.
   * @param {FamilyFindUniqueArgs} args - Arguments to find a Family
   * @example
   * // Get one Family
   * const family = await prisma.family.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FamilyFindUniqueArgs>(args: Prisma.SelectSubset<T, FamilyFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FamilyClient<runtime.Types.Result.GetResult<Prisma.$FamilyPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Family that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FamilyFindUniqueOrThrowArgs} args - Arguments to find a Family
   * @example
   * // Get one Family
   * const family = await prisma.family.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FamilyFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FamilyFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FamilyClient<runtime.Types.Result.GetResult<Prisma.$FamilyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Family that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FamilyFindFirstArgs} args - Arguments to find a Family
   * @example
   * // Get one Family
   * const family = await prisma.family.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FamilyFindFirstArgs>(args?: Prisma.SelectSubset<T, FamilyFindFirstArgs<ExtArgs>>): Prisma.Prisma__FamilyClient<runtime.Types.Result.GetResult<Prisma.$FamilyPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Family that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FamilyFindFirstOrThrowArgs} args - Arguments to find a Family
   * @example
   * // Get one Family
   * const family = await prisma.family.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FamilyFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FamilyFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FamilyClient<runtime.Types.Result.GetResult<Prisma.$FamilyPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Families that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FamilyFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Families
   * const families = await prisma.family.findMany()
   * 
   * // Get first 10 Families
   * const families = await prisma.family.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const familyWithIdOnly = await prisma.family.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FamilyFindManyArgs>(args?: Prisma.SelectSubset<T, FamilyFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FamilyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Family.
   * @param {FamilyCreateArgs} args - Arguments to create a Family.
   * @example
   * // Create one Family
   * const Family = await prisma.family.create({
   *   data: {
   *     // ... data to create a Family
   *   }
   * })
   * 
   */
  create<T extends FamilyCreateArgs>(args: Prisma.SelectSubset<T, FamilyCreateArgs<ExtArgs>>): Prisma.Prisma__FamilyClient<runtime.Types.Result.GetResult<Prisma.$FamilyPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Families.
   * @param {FamilyCreateManyArgs} args - Arguments to create many Families.
   * @example
   * // Create many Families
   * const family = await prisma.family.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FamilyCreateManyArgs>(args?: Prisma.SelectSubset<T, FamilyCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Families and returns the data saved in the database.
   * @param {FamilyCreateManyAndReturnArgs} args - Arguments to create many Families.
   * @example
   * // Create many Families
   * const family = await prisma.family.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Families and only return the `id`
   * const familyWithIdOnly = await prisma.family.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FamilyCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FamilyCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FamilyPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Family.
   * @param {FamilyDeleteArgs} args - Arguments to delete one Family.
   * @example
   * // Delete one Family
   * const Family = await prisma.family.delete({
   *   where: {
   *     // ... filter to delete one Family
   *   }
   * })
   * 
   */
  delete<T extends FamilyDeleteArgs>(args: Prisma.SelectSubset<T, FamilyDeleteArgs<ExtArgs>>): Prisma.Prisma__FamilyClient<runtime.Types.Result.GetResult<Prisma.$FamilyPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Family.
   * @param {FamilyUpdateArgs} args - Arguments to update one Family.
   * @example
   * // Update one Family
   * const family = await prisma.family.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FamilyUpdateArgs>(args: Prisma.SelectSubset<T, FamilyUpdateArgs<ExtArgs>>): Prisma.Prisma__FamilyClient<runtime.Types.Result.GetResult<Prisma.$FamilyPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Families.
   * @param {FamilyDeleteManyArgs} args - Arguments to filter Families to delete.
   * @example
   * // Delete a few Families
   * const { count } = await prisma.family.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FamilyDeleteManyArgs>(args?: Prisma.SelectSubset<T, FamilyDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Families.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FamilyUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Families
   * const family = await prisma.family.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FamilyUpdateManyArgs>(args: Prisma.SelectSubset<T, FamilyUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Families and returns the data updated in the database.
   * @param {FamilyUpdateManyAndReturnArgs} args - Arguments to update many Families.
   * @example
   * // Update many Families
   * const family = await prisma.family.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Families and only return the `id`
   * const familyWithIdOnly = await prisma.family.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FamilyUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FamilyUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FamilyPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Family.
   * @param {FamilyUpsertArgs} args - Arguments to update or create a Family.
   * @example
   * // Update or create a Family
   * const family = await prisma.family.upsert({
   *   create: {
   *     // ... data to create a Family
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Family we want to update
   *   }
   * })
   */
  upsert<T extends FamilyUpsertArgs>(args: Prisma.SelectSubset<T, FamilyUpsertArgs<ExtArgs>>): Prisma.Prisma__FamilyClient<runtime.Types.Result.GetResult<Prisma.$FamilyPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Families.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FamilyCountArgs} args - Arguments to filter Families to count.
   * @example
   * // Count the number of Families
   * const count = await prisma.family.count({
   *   where: {
   *     // ... the filter for the Families we want to count
   *   }
   * })
  **/
  count<T extends FamilyCountArgs>(
    args?: Prisma.Subset<T, FamilyCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FamilyCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Family.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FamilyAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FamilyAggregateArgs>(args: Prisma.Subset<T, FamilyAggregateArgs>): Prisma.PrismaPromise<GetFamilyAggregateType<T>>

  /**
   * Group by Family.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FamilyGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FamilyGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FamilyGroupByArgs['orderBy'] }
      : { orderBy?: FamilyGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FamilyGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFamilyGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Family model
 */
readonly fields: FamilyFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Family.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FamilyClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  collections<T extends Prisma.Family$collectionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Family$collectionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CollectionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Family model
 */
export interface FamilyFieldRefs {
  readonly id: Prisma.FieldRef<"Family", 'String'>
  readonly familyCode: Prisma.FieldRef<"Family", 'String'>
  readonly headName: Prisma.FieldRef<"Family", 'String'>
  readonly phone: Prisma.FieldRef<"Family", 'String'>
  readonly address: Prisma.FieldRef<"Family", 'String'>
  readonly monthlyFee: Prisma.FieldRef<"Family", 'Decimal'>
  readonly memberCount: Prisma.FieldRef<"Family", 'Int'>
  readonly joiningDate: Prisma.FieldRef<"Family", 'DateTime'>
  readonly status: Prisma.FieldRef<"Family", 'FamilyStatus'>
  readonly remarks: Prisma.FieldRef<"Family", 'String'>
  readonly createdAt: Prisma.FieldRef<"Family", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Family", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Family findUnique
 */
export type FamilyFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Family
   */
  select?: Prisma.FamilySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Family
   */
  omit?: Prisma.FamilyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyInclude<ExtArgs> | null
  /**
   * Filter, which Family to fetch.
   */
  where: Prisma.FamilyWhereUniqueInput
}

/**
 * Family findUniqueOrThrow
 */
export type FamilyFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Family
   */
  select?: Prisma.FamilySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Family
   */
  omit?: Prisma.FamilyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyInclude<ExtArgs> | null
  /**
   * Filter, which Family to fetch.
   */
  where: Prisma.FamilyWhereUniqueInput
}

/**
 * Family findFirst
 */
export type FamilyFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Family
   */
  select?: Prisma.FamilySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Family
   */
  omit?: Prisma.FamilyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyInclude<ExtArgs> | null
  /**
   * Filter, which Family to fetch.
   */
  where?: Prisma.FamilyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Families to fetch.
   */
  orderBy?: Prisma.FamilyOrderByWithRelationInput | Prisma.FamilyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Families.
   */
  cursor?: Prisma.FamilyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Families from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Families.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Families.
   */
  distinct?: Prisma.FamilyScalarFieldEnum | Prisma.FamilyScalarFieldEnum[]
}

/**
 * Family findFirstOrThrow
 */
export type FamilyFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Family
   */
  select?: Prisma.FamilySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Family
   */
  omit?: Prisma.FamilyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyInclude<ExtArgs> | null
  /**
   * Filter, which Family to fetch.
   */
  where?: Prisma.FamilyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Families to fetch.
   */
  orderBy?: Prisma.FamilyOrderByWithRelationInput | Prisma.FamilyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Families.
   */
  cursor?: Prisma.FamilyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Families from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Families.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Families.
   */
  distinct?: Prisma.FamilyScalarFieldEnum | Prisma.FamilyScalarFieldEnum[]
}

/**
 * Family findMany
 */
export type FamilyFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Family
   */
  select?: Prisma.FamilySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Family
   */
  omit?: Prisma.FamilyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyInclude<ExtArgs> | null
  /**
   * Filter, which Families to fetch.
   */
  where?: Prisma.FamilyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Families to fetch.
   */
  orderBy?: Prisma.FamilyOrderByWithRelationInput | Prisma.FamilyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Families.
   */
  cursor?: Prisma.FamilyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Families from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Families.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Families.
   */
  distinct?: Prisma.FamilyScalarFieldEnum | Prisma.FamilyScalarFieldEnum[]
}

/**
 * Family create
 */
export type FamilyCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Family
   */
  select?: Prisma.FamilySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Family
   */
  omit?: Prisma.FamilyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyInclude<ExtArgs> | null
  /**
   * The data needed to create a Family.
   */
  data: Prisma.XOR<Prisma.FamilyCreateInput, Prisma.FamilyUncheckedCreateInput>
}

/**
 * Family createMany
 */
export type FamilyCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Families.
   */
  data: Prisma.FamilyCreateManyInput | Prisma.FamilyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Family createManyAndReturn
 */
export type FamilyCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Family
   */
  select?: Prisma.FamilySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Family
   */
  omit?: Prisma.FamilyOmit<ExtArgs> | null
  /**
   * The data used to create many Families.
   */
  data: Prisma.FamilyCreateManyInput | Prisma.FamilyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Family update
 */
export type FamilyUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Family
   */
  select?: Prisma.FamilySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Family
   */
  omit?: Prisma.FamilyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyInclude<ExtArgs> | null
  /**
   * The data needed to update a Family.
   */
  data: Prisma.XOR<Prisma.FamilyUpdateInput, Prisma.FamilyUncheckedUpdateInput>
  /**
   * Choose, which Family to update.
   */
  where: Prisma.FamilyWhereUniqueInput
}

/**
 * Family updateMany
 */
export type FamilyUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Families.
   */
  data: Prisma.XOR<Prisma.FamilyUpdateManyMutationInput, Prisma.FamilyUncheckedUpdateManyInput>
  /**
   * Filter which Families to update
   */
  where?: Prisma.FamilyWhereInput
  /**
   * Limit how many Families to update.
   */
  limit?: number
}

/**
 * Family updateManyAndReturn
 */
export type FamilyUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Family
   */
  select?: Prisma.FamilySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Family
   */
  omit?: Prisma.FamilyOmit<ExtArgs> | null
  /**
   * The data used to update Families.
   */
  data: Prisma.XOR<Prisma.FamilyUpdateManyMutationInput, Prisma.FamilyUncheckedUpdateManyInput>
  /**
   * Filter which Families to update
   */
  where?: Prisma.FamilyWhereInput
  /**
   * Limit how many Families to update.
   */
  limit?: number
}

/**
 * Family upsert
 */
export type FamilyUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Family
   */
  select?: Prisma.FamilySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Family
   */
  omit?: Prisma.FamilyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyInclude<ExtArgs> | null
  /**
   * The filter to search for the Family to update in case it exists.
   */
  where: Prisma.FamilyWhereUniqueInput
  /**
   * In case the Family found by the `where` argument doesn't exist, create a new Family with this data.
   */
  create: Prisma.XOR<Prisma.FamilyCreateInput, Prisma.FamilyUncheckedCreateInput>
  /**
   * In case the Family was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FamilyUpdateInput, Prisma.FamilyUncheckedUpdateInput>
}

/**
 * Family delete
 */
export type FamilyDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Family
   */
  select?: Prisma.FamilySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Family
   */
  omit?: Prisma.FamilyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyInclude<ExtArgs> | null
  /**
   * Filter which Family to delete.
   */
  where: Prisma.FamilyWhereUniqueInput
}

/**
 * Family deleteMany
 */
export type FamilyDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Families to delete
   */
  where?: Prisma.FamilyWhereInput
  /**
   * Limit how many Families to delete.
   */
  limit?: number
}

/**
 * Family.collections
 */
export type Family$collectionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Collection
   */
  select?: Prisma.CollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Collection
   */
  omit?: Prisma.CollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CollectionInclude<ExtArgs> | null
  where?: Prisma.CollectionWhereInput
  orderBy?: Prisma.CollectionOrderByWithRelationInput | Prisma.CollectionOrderByWithRelationInput[]
  cursor?: Prisma.CollectionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CollectionScalarFieldEnum | Prisma.CollectionScalarFieldEnum[]
}

/**
 * Family without action
 */
export type FamilyDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Family
   */
  select?: Prisma.FamilySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Family
   */
  omit?: Prisma.FamilyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyInclude<ExtArgs> | null
}
